S01US01ShowBook
WildCodeSchool-2023-09/PHP-paris-p2-book pull request #11
Opened 2023-11-09 16:37 UTC by 2z75

Hey !!
 I hope you will enjoy this US, this is the page of a Book ! This book is in the database !!

2023-11-12 21:40 UTC, mickaellambert requested changes

2023-11-12 21:40 UTC, mickaellambert commented on public/assets/css/mobile.css
> +        background-color: var(--color-background);
indentation

2023-11-12 21:40 UTC, mickaellambert commented on public/assets/css/mobile.css
> +/* p {
commentaire inutile

2023-11-12 21:40 UTC, mickaellambert commented on public/assets/css/mobile.css
> +width : 100%;
indentation

2023-11-12 21:40 UTC, mickaellambert commented on src/Controller/BookController.php
> +        $BookEditionManager = new BookEditionManager();
Pas de majuscule pour la premiere lettre au nom des variables

2023-11-12 21:40 UTC, mickaellambert commented on src/Model/BookEditionManager.php
> +    public function selectOneById(int $id): array|false
Bravo c'est très bien cette fonction est niquelle

2023-11-12 21:40 UTC, mickaellambert commented on src/View/Book/index.html.twig
Je suis pas censé voir des modifications pour la page de tous les livres sur l'US concernant l'affichage d'un livre

2023-11-12 21:40 UTC, mickaellambert commented on src/View/Book/show.html.twig
> +      <hr class="separation" />
indentation un peu bizarre ici

2023-11-12 21:40 UTC, mickaellambert commented on src/View/Home/index.html.twig
Haha j'ai bien aimé j'ai rigolé mais JAMAIS tu envoies ça dans une PR

2023-11-12 21:40 UTC, mickaellambert commented on src/View/_header.html.twig
Pareil, ici tu veux faire un fix sur ton header et tu l'incrustes dans une PR qui n'a rien à voir avec. 
Il aurait fallu que tu repartes de dev, que tu recréés une branche "fix_header", que tu modifies juste ça et que tu me fasses une PR de la branche "fix_header" vers "dev"

2023-11-16 08:26 UTC, 2z75 commented on src/Model/BookEditionManager.php
> +    public function selectOneById(int $id): array|false
merci !

2023-11-16 08:26 UTC, 2z75 commented on src/Controller/BookController.php
> +        $BookEditionManager = new BookEditionManager();
c'est le stress c'est le stress

2023-11-16 09:55 UTC, mickaellambert requested changes

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +        background-color: var(--color-background);
Indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +color: var(--Second, #9D244D);
Indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +color: #947982;
Indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +/* p {
Pas de commentaire inutile

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +width : 100%;
indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +display: column;
indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/desktop.css
> +align-items: flex-start;
indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/mobile.css
> +width: 100%;
indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/mobile.css
> +height: auto;
indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/mobile.css
> +background-color: var(--color-background);
indentation pas bonne

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/css/style.css
Pourquoi m'envoyer cette modificatin ?

2023-11-16 09:55 UTC, mickaellambert commented on src/View/Book/show.html.twig
> +
trop d'espace

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/js/scriptShow.js
A renommer

2023-11-16 09:55 UTC, mickaellambert commented on public/assets/images/Add.png
A renommer

2023-11-20 08:27 UTC, mickaellambert requested changes

2023-11-20 08:27 UTC, mickaellambert commented on public/assets/images/harryPotter2cover.jpg
Ca dégage

2023-11-20 10:24 UTC, mickaellambert approved these changes

2023-11-20 10:24 UTC, merged