S1 US02 add a book
WildCodeSchool-2023-09/PHP-paris-p2-book pull request #12
Opened 2023-11-13 13:52 UTC by ElieBendier

US is finished :
- page with the form exists
- css is responsive
- js for dynamics
- errors are managed in back-end
- routing in the different cases is done
- insert in the BDD works well and there is no duplicate informations

2023-11-13 15:08 UTC, mickaellambert requested changes

2023-11-13 15:08 UTC, mickaellambert commented on migration.php
> +            $statement = $pdo->prepare("INSERT INTO " . BookManager::GENRE_TABLE . " (label) VALUES (:label);");
Ici, j'aurai créé un fichier GenreManager vide avec juste la surcharge de la constante TABLE. 
Ca permet d'utiliser GenreManager::TABLE et c'est plus joli !

2023-11-13 15:08 UTC, mickaellambert commented on migration.php
> +            $statement->bindValue(':label', $genre);
T'avais pas forcément besoin de faire de prepare ici étant donné que les données ne sont pas dynamiques du tout, c'est bien toi qui lui fournis

2023-11-13 15:08 UTC, mickaellambert commented on public/assets/css/desktop.css
> +form {
Donc TOUS les form de votre application auront un padding: 0 20% ?

2023-11-13 15:08 UTC, mickaellambert commented on public/assets/css/mobile.css
> +form {
Même remarque ici, sélectionner en CSS avec le simple selecteur "form" c'est un peu dangereux, je serai un peu plus précis à ta place

2023-11-13 15:08 UTC, mickaellambert commented on public/assets/css/mobile.css
> +form #element1 {
element1 ?

2023-11-13 15:08 UTC, mickaellambert commented on public/assets/css/mobile.css
> +form input::placeholder,
tous les select, tous les place holder des textarea et des input de toute ton application auront ces propriétés CSS la

2023-11-13 15:08 UTC, mickaellambert commented on public/assets/js/read.js
> +button1.addEventListener("click", () => {
button1 ?

2023-11-13 15:08 UTC, mickaellambert commented on public/uploads/65522767a549c.jpeg
Le dossier d'upload doit se trouver dans le .gitignore

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +    public function addForm()
Ici, tu peux juste appeler ta fonction add, pas besoin de préciser que c'est un form

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            $this->checkIfError($book);
petit espace juste au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            if (empty($this->errors)) {
petit espace juste au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +                if (!$bookManager->checkIfBookExists($book) || !$bookManager->checkIfEditorExists($book)) {
petit espace juste au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +                    foreach ($checks as $checkFunction => $insertFunction) {
haha pas mal allez j'accepte

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +                    $id = $bookManager->insertIntoBookEditor($book, $this->manageCover());
naming pas fou encore ici, $insertedBookId serait mieux

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +                    if ($this->formChoice($book) === "notyet") {
J'aurai plus utilisé des booléens ici plutôt que deux string random
Et utilise directement la donnée que tu récupères dans le form

En gros, tu fais directement dans le controleur un : 

```
if ($book['choice'] === self::FORM_ADD_BOOK_READ) {
       header('Location:/library/show?id=' . $id);
       exit();
}
```

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +                    $id = $bookManager->findBook($book);
ca c'est bien en terme d'ux !

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +    public function checkIfError($book)
j'appelerai cette fonction checksAddForm()

check = forcément gestion d'erreur
et addForm = t'auras surement d'autres formulaire plus tard dans ce controlleur

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +    public function checkIfErrorGenre($book)
cf comm du dessus

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +    public function manageCover()
manageCoverAddForm

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            $authorizedExtensions = ['jpeg', 'jpg' ,'png', 'gif', 'webp',];
ca pourrait être interessant de mettre ce tableau en constante du controller

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            $maxFileSize = 1000000;
pareil qu'au dessus

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            $coverExtension = $cover['type'];
pourquoi assigner une variable $coverExtension ici ? 
Autant utiliser $cover['type'] partout non ?

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            if (!in_array($coverExtension, $authorizedExtensions)) {
espace au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            if (file_exists($cover['tmp_name']) && $cover['size'] > $maxFileSize) {
espace au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            $uploadDir = 'uploads/';
espace au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            $uploadDir = 'uploads/';
Peut être en faire une constante dans ton fichier de configuration, comme ça tu peux la réutiliser ou tu veux

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            return $uploadFile;
espace moi tout ça stp haha

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +        if (empty($_FILES['book_editor_cover']['name'][0])) {
espace au dessus stp

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            return $uploadFile;
pas besoin de cette ligne ici, tu feras le return à la toute fin de fonction

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            return $uploadFile = "assets/images/cover_question_mark.png";
pas besoin du return ici, tu peux juste faire ton affectation `$uploadFile = "assets/images/cover_question_mark.png";`

Tu viens faire un return $uploadFile à la toute fin de fonction

En gros, t'affectes la valeur de $uploadFile dans toutes tes conditions et à la fin tu le return

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +    public function formChoice($book): string
A supprimer du coup

2023-11-13 15:08 UTC, mickaellambert commented on src/Model/BookManager.php
> +    public const BOOK_EDITOR_TABLE = 'book_editor';
A mettre dans chaque manager correspondant .. Désolé <3

2023-11-13 15:08 UTC, mickaellambert commented on src/Model/BookManager.php
> +        $bookId = $this->getBookId($book);
Je pense qu'on peut récuper un bookId (soit ajouté, soit déjà présent) grâce au passage de paramètre et non via une requête SQL (optimisation de perf)

2023-11-13 15:08 UTC, mickaellambert commented on src/Model/BookManager.php
> +        $statement = $this->pdo->query("SELECT * FROM " . self::AUTHOR_TABLE . ";");
Tu peux faire le check en SQL direct

2023-11-13 15:08 UTC, mickaellambert commented on src/Model/BookManager.php
> +        $statement = $this->pdo->query("SELECT * FROM " . self::GENRE_TABLE . ";");
pareil que au dessus

2023-11-13 15:08 UTC, mickaellambert commented on src/View/Book/_addForm.html.twig
petit probleme de naming, 

soit _form.html.twig et du coup utilisable par le add et le edit
soit formAdd.html.twig

2023-11-13 15:08 UTC, mickaellambert commented on src/Controller/BookController.php
> +            'genres' => BookManager::GENRES,
Tu peux directement utiliser la constante dans la vue via Twig : https://twig.symfony.com/doc/3.x/functions/constant.html

2023-11-13 15:08 UTC, mickaellambert commented on src/View/Book/_addForm.html.twig
> +					{% for genre in genres %}
Utiliser la constante https://twig.symfony.com/doc/3.x/functions/constant.html

2023-11-13 15:08 UTC, mickaellambert commented on src/View/layout.html.twig
> +	<head>
petit souci d'indentation ici

2023-11-13 15:08 UTC, mickaellambert commented on src/View/layout.html.twig
> +			<script src="/assets/js/read.js"></script>
A redéfinir directement dans la vue formAdd

2023-11-13 15:08 UTC, mickaellambert commented on src/routes.php
> +    'book/add' => ['BookController', 'addForm',],
Laisse juste la tienne

2023-11-13 15:34 UTC, nicolasalibert approved these changes

2023-11-14 11:20 UTC, ElieBendier commented on public/assets/css/desktop.css
> +form {
done

2023-11-14 11:20 UTC, ElieBendier commented on public/assets/css/mobile.css
> +form {
done

2023-11-14 11:24 UTC, ElieBendier commented on public/assets/css/mobile.css
> +form #element1 {
done

2023-11-14 11:26 UTC, ElieBendier commented on src/View/layout.html.twig
> +	<head>
done

2023-11-14 11:30 UTC, ElieBendier commented on src/View/layout.html.twig
> +			<script src="/assets/js/read.js"></script>
done

2023-11-14 11:31 UTC, ElieBendier commented on src/routes.php
> +    'book/add' => ['BookController', 'addForm',],
done

2023-11-14 11:34 UTC, ElieBendier commented on public/assets/css/mobile.css
> +form input::placeholder,
done

2023-11-14 11:35 UTC, ElieBendier commented on public/assets/js/read.js
> +button1.addEventListener("click", () => {
done

2023-11-20 08:39 UTC, mickaellambert approved these changes

2023-11-20 10:20 UTC, mickaellambert approved these changes

2023-11-21 08:21 UTC, merged