initialized project structure & database
WildCodeSchool-2023-09/PHP-paris-p2-book pull request #2
Opened 2023-10-31 16:42 UTC by nicolasalibert

:)

2023-10-31 16:43 UTC, ElieBendier approved these changes
bon boulot

2023-11-02 16:20 UTC, mickaellambert reviewed
Vous pourriez rajouter les premières variables CSS aussi

Faites attention en revanche sur l'architecture des dossiers de vos vues, vous avez gardé la nomenclature "Item", je suis pas sur que c'est ce que vous voulez vraiment :)

2023-11-02 16:20 UTC, mickaellambert requested changes
CF 1ere revue

2023-11-06 13:43 UTC, mickaellambert approved these changes

2023-11-06 13:43 UTC, merged