Navbar
WildCodeSchool-2023-09/PHP-paris-p2-book pull request #3
Opened 2023-11-03 10:01 UTC by nicolasalibert

Worked on navbar - still needs work

2023-11-07 13:14 UTC, mickaellambert requested changes

2023-11-07 13:14 UTC, mickaellambert commented on public/assets/images/icon-add.png
J'aime bien ce naming, parle en à Eddy qui a fait un dossier icons et qui a mis des images dedans. Ca va être bizarre lorsqu'on va merger tout votre travail

2023-11-07 13:14 UTC, mickaellambert commented on config/db.php.dist
Pas besoin de modifier ce fichier normalement même si je comprends le principe
Et puis nous sommes dans une PR Navbar, normalement je suis censé avoir que ce qui touche à la navbar

2023-11-07 13:14 UTC, mickaellambert commented on src/View/Item/_footer.html.twig
On garde l'arborescence des dossiers Item du coup ?

2023-11-07 14:29 UTC, nicolasalibert commented on src/View/Item/_footer.html.twig
on est passés sur 'Book'

2023-11-07 14:30 UTC, nicolasalibert commented on public/assets/images/icon-add.png
ok on voit ça !

2023-11-07 14:31 UTC, nicolasalibert commented
j'ai terminé la navbar, il manque seulement le marque page derrière l'icône de la section ouverte, je verrai comment faire plus tard

2023-11-07 15:54 UTC, mickaellambert requested changes

2023-11-07 15:54 UTC, mickaellambert commented on public/assets/js/navbar.js
> +console.log("js script working");
Ca il faut le virer

2023-11-07 15:54 UTC, mickaellambert commented on public/assets/js/navbar.js
> +userBtn.addEventListener('click', function() {
Je crois que t'as une fonction JS toggle() qui permet de faire ça

2023-11-07 15:54 UTC, mickaellambert commented on public/assets/js/navbar.js
> +    console.log("opened user menu");
Console.log

2023-11-07 15:54 UTC, mickaellambert commented on public/assets/js/navbar.js
> +    console.log("closed user menu");
Console.log

2023-11-07 15:54 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +    <p>zizi.</p>
OUPSI

2023-11-07 15:54 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +{# {% block navbar %}
Commentaire inutile

2023-11-08 16:04 UTC, mickaellambert approved these changes

2023-11-08 16:05 UTC, merged