S1 US01 homepage guest
WildCodeSchool-2023-09/PHP-paris-p2-book pull request #6
Opened 2023-11-06 14:41 UTC by KarlRow

Homepage the website for the user guest.

- Home Header with title
- Somes content to inform the guest user to show the principal features

2023-11-06 15:06 UTC, mickaellambert requested changes

2023-11-06 15:06 UTC, mickaellambert commented on public/assets/css/style.css
> +@media only screen and (max-width: 480px){
La media query se fera au niveau de l'inclusion du fichier, pas directement dans le CSS

2023-11-06 15:06 UTC, mickaellambert commented on public/assets/css/style.css
> +    @font-face{
saute des lignes entre chaque selecteur CSS stp

2023-11-06 15:06 UTC, mickaellambert commented on public/assets/icons/Heart.svg
Ces fichiers commencent par une majuscule, tandis que les autres images commencent par une minuscule

2023-11-06 15:06 UTC, mickaellambert commented on public/assets/icons/book.png
attention, deux fichiers book envoyés ici un .png et un .svg

2023-11-06 15:06 UTC, mickaellambert commented on src/View/Book/_header.html.twig
Voulais tu vraiment modifier ce fichier ? A voir pendant la relecture

2023-11-06 15:06 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +        {# header homepage-guest #}
pas de commentaire inutile

2023-11-06 15:06 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +        {# Body homepage #}
Pas de commentaire inutile stp

2023-11-06 15:06 UTC, mickaellambert commented on src/View/Home/index.html.twig
> +                                <img src="../../assets/icons/book.svg" alt="book icon">
Parfois, tu as un chemin qui commence par "../../assets" et d'autres fois juste par "../assets"

2023-11-06 15:28 UTC, KarlRow commented on src/View/Home/index.html.twig
> +                                <img src="../../assets/icons/book.svg" alt="book icon">
En effet, c'est corrigé.

2023-11-06 15:28 UTC, KarlRow commented on src/View/Home/index.html.twig
> +        {# Body homepage #}
C'est corrigé.

2023-11-06 15:29 UTC, KarlRow commented on src/View/Home/index.html.twig
> +        {# header homepage-guest #}
C'est corrigé.

2023-11-06 15:33 UTC, KarlRow commented on src/View/Book/_header.html.twig
Non, car la homepage guest contient une header unique qui n'a pas besoin d'être rappelé dans la page _header.html.twig

2023-11-06 15:34 UTC, KarlRow commented on public/assets/icons/book.png
Ok, suppression du fichier .png

2023-11-06 15:34 UTC, KarlRow commented on public/assets/icons/Heart.svg
Ok, c'est corrigé.

2023-11-06 15:34 UTC, KarlRow commented on public/assets/css/style.css
> +    @font-face{
C'est corrigé.

2023-11-07 13:10 UTC, mickaellambert requested changes
T'as toujours des noms de fichiers d'image qui commencent par une majuscule, attention !

2023-11-08 14:18 UTC, closed without merging